### ISSUE TITLE
Innholdsfortegnelse foran cookie-varsel

### ISSUE THREAD

**Issue by macbruker** [oslokommune/labs.oslo.kommune.no#48]
Oppdaget at innholdsfortegnelsen i artikler legger seg foran cookie-varselet. 
![Image](https://github.com/user-attachments/assets/1c69a6f0-5f71-431f-a15b-daa6c4987ad9)

Ser ut til å fikses med `z-index: 1` på `.app-cookie-line`.

**Comment by nerdegutt** [comment]
Takk, @macbruker ! Forbilledlig innmelding av feil (og løsning). Har sjekka inn en fiks nå. I prod så snart actions har gjort jobben sin
